import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "./images/Adidas Shoes 1.jpg",
    title: " Adidas Supersta ",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$200",
    newPrice: "$100",
    company: "Adidas",
    color: "white",
    category: "shoes",
  },
  {
    img: "./images/Adidas Shoes 2.jpg",
    title: "Adidas Ultraboost",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$50",
    company: "Adidas",
    color: "black",
    category: "shoes",
  },

  {
    img: "./images/Adidas Shoes 3.jpg",
    title: "Adidas Stan Smith",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$100",
    company: "Adidas",
    color: "white",
    category: "shoes",
  },
  {
    img: "./images/Adidas Shoes 4.jpg",
    title: "Adidas NMD",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$150",
    company: "Adidas",
    color: "black",
    category: "shoes",
  },
  {
    img: "./images/Adidas Shoes 5.jpg",
    title: "Adidas Gazelle",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$200",
    company: "Adidas",
    color: "white",
    category: "shoes",
  },
  {
    img: "./images/Adidas Sneaker 1.jpg",
    title: " Adidas Ultra Boost",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$50",
    company: "Adidas",
    color: "blue",
    category: "sneaker",
  },

  {
    img: "./images/Adidas Sneaker 2.jpg",
    title: " Adidas NMD",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$100",
    company: "Adidas",
    color: "black",
    category: "sneaker",
  },

  {
    img: "./images/Adidas Sneaker 3.jpg",
    title: "Adidas Yeezy Boost",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$100",
    company: "Adidas",
    color: "black",
    category: "sneaker",
  },

  {
    img: "./images/Adidas Sneaker 4.jpg",
    title: "Adidas Superstar",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$150",
    company: "Adidas",
    color: "white",
    category: "sneaker",
  },

  {
    img: "./images/Adidas Sneaker 5.jpg",
    title: "Adidas Stan Smith",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$200",
    company: "Adidas",
    color: "white",
    category: "sneaker",
  },
  {
    img: "./images/Nike shoes 1.jpg",
    title: "Nike Air Maxr",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$150",
    company: "Nike",
    color: "blue",
    category: "shoes",
  },
  {
    img: "./images/Nike shoes 2.jpg",
    title: "Nike Air Jordan",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$200",
    company: "Nike",
    color: "red",
    category: "shoes",
  },
  {
    img: "./images/Nike shoes 3.jpg",
    title: "Nike Free Run",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$100",
    company: "Nike",
    color: "blue",
    category: "shoes",
  },
  {
    img: "./images/Nike shoes 4.jpg",
    title: "Nike Cortez",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$150",
    company: "Nike",
    color: "black",
    category: "shoes",
  },

  {
    img: "./images/Nike shoes 5.jpg",
    title: "Nike Roshe Run",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$50",
    company: "Nike",
    color: "white",
    category: "shoes",
  },
  {
    img: "./images/Nike Sneaker 1.jpg",
    title: "Nike Air Max",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$100",
    company: "Nike",
    color: "black",
    category: "sneaker",
  },
  {
    img: "./images/Nike Sneaker 2.jpg",
    title: "Nike Zoom",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$150",
    company: "Nike",
    color: "white",
    category: "sneaker",
  },
  {
    img: "./images/Nike Sneaker 3.jpg",
    title: "Nike Cortez",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$200",
    company: "Nike",
    color: "white",
    category: "sneaker",
  },
  {
    img: "./images/Nike Sneaker 4.jpg",
    title: "Nike Air Force 1",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$100",
    company: "Nike",
    color: "white",
    category: "sneaker",
  },
  {
    img: "./images/Nike Sneaker 5.jpg",
    title: " Nike Free Run",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$150",
    company: "Nike",
    color: "black",
    category: "sneaker",
  },
  {
    img: "./images/Puma Shoes 1.jpg",
    title: " PUMA Suede Classic",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$150",
    company: "Puma",
    color: "red",
    category: "shoes",
  },
  {
    img: "./images/Puma Shoes 2.jpg",
    title: "PUMA RS-X",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$100",
    company: "Puma",
    color: "black",
    category: "shoes",
  },
  {
    img: "./images/Puma Shoes 3.jpg",
    title: "PUMA Clyde Court",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$100",
    company: "Puma",
    color: "black",
    category: "shoes",
  },

  {
    img: "./images/Puma Shoes 4.jpg",
    title: " PUMA Cell Venom",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$100",
    company: "Puma",
    color: "black",
    category: "shoes",
  },
  {
    img: "./images/Puma Shoes 5.jpg",
    title: "PUMA Thunder Desert",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$100",
    company: "Puma",
    color: "black",
    category: "shoes",
  },
  {
    img: "./images/Puma Sneaker 1.jpg",
    title: " PUMA RS-X",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$150",
    company: "Puma",
    color: "black",
    category: "sneaker",
  },
  {
    img: "./images/Puma Sneaker 2.jpg",
    title: "PUMA Suede Classic",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$50",
    company: "Puma",
    color: "white",
    category: "sneaker",
  },
  {
    img: "./images/Puma Sneaker 3.jpg",
    title: " PUMA Clyde Court",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$100",
    company: "Puma",
    color: "black",
    category: "sneaker",
  },
  {
    img: "./images/Puma Sneaker 4.jpg",
    title: " PUMA Future Rider",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$100",
    company: "Puma",
    color: "white",
    category: "sneaker",
  },
  {
    img: "./images/Puma Sneaker 5.jpg",
    title: " PUMA Call",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$50",
    company: "Puma",
    color: "white",
    category: "sneaker",
  },{
    img: "./images/Jimmy Choo 1.jpg",
    title: "Romy",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$150",
    company: "Jimmy",
    color: "black",
    category: "heels",
  },
  {
    img: "./images/Jimmy Choo 2.jpg",
    title: "Lance",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$100",
    company: "Jimmy",
    color: "white",
    category: "heels",
  },
  {
    img: "./images/Jimmy Choo 3.jpg",
    title: "Abel",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$100",
    company: "Jimmy",
    color: "golden",
    category: "heels",
  },
  {
    img: "./images/Jimmy Choo 4.jpg",
    title: "Emily",
    star: <AiFillStar className="ratings-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "$100",
    company: "Jimmy",
    color: "black",
    category: "heels",
  },
  

];

export default data;